DATABASE_NAME = "gitsync"
GIT_PREFIX = "git"
OBJECTS_COLL_NAME = "~objects"
REPOS_COLL_NAME = "~repos"
LOCAL_CMD_PREFIX = "/localhost/gitsync"

PUSH_RESPONSE_PENDING = 0
PUSH_RESPONSE_SUCCESS = 1
PUSH_RESPONSE_FAILURE = 2

MOUNT_PATH = "~/.gitsync/~mount"
